name: kmer
channels:
- bioconda
- defaults
dependencies:
- argh=0.26.1=py27_0
- gffutils=0.9=py27_0
- pyfaidx=0.5.0=py27_0
- argcomplete=1.0.0=py27_1
- backports=1.0=py27_0
- backports.weakref=1.0rc1=py27_0
- backports_abc=0.5=py27_0
- biopython=1.69=np113py27_0
- bleach=1.5.0=py27_0
- cairo=1.14.8=0
- certifi=2016.2.28=py27_0
- cycler=0.10.0=py27_0
- dbus=1.10.20=0
- decorator=4.1.2=py27_0
- enum34=1.1.6=py27_0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- funcsigs=1.0.2=py27_0
- functools32=3.2.3.2=py27_0
- get_terminal_size=1.0.0=py27_0
- glib=2.50.2=1
- graphviz=2.38.0=5
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.7.0=np113py27_0
- harfbuzz=0.9.39=2
- hdf5=1.8.17=2
- html5lib=0.9999999=py27_0
- icu=54.1=0
- ipykernel=4.6.1=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- jbig=2.1=0
- joblib=0.11=py27_0
- jpeg=9b=0
- jupyter_client=5.1.0=py27_0
- jupyter_core=4.3.0=py27_0
- keras=2.0.5=py27_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libgpuarray=0.6.9=0
- libiconv=1.14=0
- libpng=1.6.30=1
- libprotobuf=3.4.0=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libtool=2.4.2=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- lmdb=0.9.21=0
- mako=1.0.6=py27_0
- markdown=2.6.9=py27_0
- markupsafe=1.0=py27_0
- matplotlib=2.0.2=np113py27_0
- mkl=2017.0.3=0
- mkl-service=1.1.2=py27_3
- mock=2.0.0=py27_0
- networkx=1.11=py27_0
- nose=1.3.7=py27_1
- numpy=1.13.1=py27_0
- openssl=1.0.2l=0
- pandas=0.20.3=py27_0
- pango=1.40.3=1
- path.py=10.3.1=py27_0
- pathlib2=2.3.0=py27_0
- pbr=1.10.0=py27_0
- pcre=8.39=1
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- prompt_toolkit=1.0.15=py27_0
- protobuf=3.4.0=py27_0
- ptyprocess=0.5.2=py27_0
- pycairo=1.10.0=py27_0
- pydot=1.0.28=py27_0
- pyflakes=1.6.0=py27_0
- pygments=2.2.0=py27_0
- pygpu=0.6.9=py27_0
- pyparsing=1.5.6=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=0
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- pyyaml=3.12=py27_0
- pyzmq=16.0.2=py27_0
- qt=5.6.2=5
- readline=6.2=2
- scandir=1.5=py27_0
- scikit-learn=0.19.0=np113py27_0
- scipy=0.19.1=np113py27_0
- setuptools=36.4.0=py27_0
- simplegeneric=0.8.1=py27_1
- simplejson=3.11.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.5.0.1=py27_0
- subprocess32=3.2.7=py27_0
- tabulate=0.7.5=py27_0
- tensorflow=1.3.0=0
- tensorflow-base=1.3.0=py27_0
- tensorflow-tensorboard=0.1.5=py27_0
- theano=0.9.0=py27_0
- tk=8.5.18=0
- tornado=4.5.2=py27_0
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- werkzeug=0.12.2=py27_0
- wheel=0.29.0=py27_0
- xz=5.2.3=0
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.11=0
- pip:
  - astroid==1.5.3
  - backports-abc==0.5
  - backports.functools-lru-cache==1.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - brewer2mpl==1.4.1
  - chardet==3.0.4
  - configparser==3.5.0
  - coverage==4.4.2
  - definitions==0.2.0
  - entrypoints==0.2.3
  - future==0.16.0
  - ggplot==0.11.5
  - hyperas==0.4
  - hyperopt==0.1
  - idna==2.6
  - imbalanced-learn==0.3.1
  - imblearn==0.0
  - ipython-genutils==0.2.0
  - ipywidgets==7.0.1
  - isodate==0.6.0
  - isort==4.2.15
  - jinja2==2.9.6
  - jsonschema==2.6.0
  - jupyter==1.0.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - lazy-object-proxy==1.3.1
  - mccabe==0.6.1
  - mistune==0.7.4
  - nbconvert==5.3.1
  - nbformat==4.4.0
  - nose2==0.7.2
  - notebook==5.1.0
  - pandocfilters==1.4.2
  - patsy==0.4.1
  - prompt-toolkit==1.0.15
  - pycodestyle==2.3.1
  - pydocstyle==2.0.0
  - pylama==7.4.3
  - pylama-pylint==3.0.1
  - pylint==1.7.2
  - pymongo==3.5.1
  - qtconsole==4.3.1
  - rdflib==4.2.2
  - requests==2.18.4
  - snowballstemmer==1.2.1
  - sparqlwrapper==1.8.0
  - statsmodels==0.8.0
  - terminado==0.6
  - testpath==0.3.1
  - urllib3==1.22
  - widgetsnbextension==3.0.3
  - wrapt==1.10.11

