k: [7, 9]
model: ['neural_network', 'support_vector_machine', 'random_forest']
selection: ['kbest']
filter: ['complete']
prediction: ['Host', 'Htype', 'Lineage', 'Otype', 'Serotype']
important_features_models: ['support_vector_machine', 'random_forest']
reps: 100
