augment: null
augment_args: {}
data_args:
  kwargs:
    blacklist: [ECI-2624, ECI-2859, ECI-2836]
    fasta_header: Strain
    train_header: None
model_args: {}
scaler: scale_to_range
scaler_args: {high: 1, low: -1}
selection: select_k_best
selection_args: {k: 270, score_func: f_classif}
validate: true
